@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AbstractApplicationContext
class AbstractAutowireCapableBeanFactory
class AbstractBeanFactory
interface AliasRegistry << interface >>
interface ApplicationContext << interface >>
interface AutowireCapableBeanFactory << interface >>
interface BeanDefinitionRegistry << interface >>
interface BeanFactory << interface >>
interface ConfigurableBeanFactory << interface >>
interface ConfigurableListableBeanFactory << interface >>
note left:这个接口下文要看
class DefaultListableBeanFactory
class DefaultSingletonBeanRegistry
class FactoryBeanRegistrySupport
interface HierarchicalBeanFactory << interface >>
interface ListableBeanFactory << interface >>
class SimpleAliasRegistry
interface SingletonBeanRegistry << interface >>

AbstractApplicationContext          -[#008200,dashed]-^  ApplicationContext                 
AbstractAutowireCapableBeanFactory  -[#000082,plain]-^  AbstractBeanFactory                
AbstractAutowireCapableBeanFactory  -[#008200,dashed]-^  AutowireCapableBeanFactory         
AbstractBeanFactory                 -[#008200,dashed]-^  ConfigurableBeanFactory            
AbstractBeanFactory                 -[#000082,plain]-^  FactoryBeanRegistrySupport         
ApplicationContext                  -[#008200,plain]-^  HierarchicalBeanFactory            
ApplicationContext                  -[#008200,plain]-^  ListableBeanFactory                
AutowireCapableBeanFactory          -[#008200,plain]-^  BeanFactory                        
BeanDefinitionRegistry              -[#008200,plain]-^  AliasRegistry                      
ConfigurableBeanFactory             -[#008200,plain]-^  HierarchicalBeanFactory            
ConfigurableBeanFactory             -[#008200,plain]-^  SingletonBeanRegistry              
ConfigurableListableBeanFactory     -[#008200,plain]-^  AutowireCapableBeanFactory         
ConfigurableListableBeanFactory     -[#008200,plain]-^  ConfigurableBeanFactory            
ConfigurableListableBeanFactory     -[#008200,plain]-^  ListableBeanFactory                
DefaultListableBeanFactory          -[#000082,plain]-^  AbstractAutowireCapableBeanFactory 
DefaultListableBeanFactory          -[#008200,dashed]-^  BeanDefinitionRegistry             
DefaultListableBeanFactory          -[#008200,dashed]-^  ConfigurableListableBeanFactory    
DefaultSingletonBeanRegistry        -[#000082,plain]-^  SimpleAliasRegistry                
DefaultSingletonBeanRegistry        -[#008200,dashed]-^  SingletonBeanRegistry              
FactoryBeanRegistrySupport          -[#000082,plain]-^  DefaultSingletonBeanRegistry       
HierarchicalBeanFactory             -[#008200,plain]-^  BeanFactory                        
ListableBeanFactory                 -[#008200,plain]-^  BeanFactory                        
SimpleAliasRegistry                 -[#008200,dashed]-^  AliasRegistry                      
@enduml
